"""
Auto-Documentation Agent Service
Generates markdown documentation from pipeline code
"""
from typing import Optional
from services.llm_service import LLMService


class DocumentationAgent:
    def __init__(self, llm_service: LLMService):
        self.llm_service = llm_service
    
    def generate_docs(
        self, 
        pipeline_code: str,
        dag_code: Optional[str] = None
    ) -> str:
        """
        Generate comprehensive markdown documentation
        """
        # Get LLM-generated documentation
        llm_docs = self.llm_service.generate_documentation(pipeline_code, dag_code)
        
        # Add standard sections
        full_docs = self._add_standard_sections(llm_docs, pipeline_code, dag_code)
        
        return full_docs
    
    def _add_standard_sections(
        self, 
        llm_docs: str,
        pipeline_code: str,
        dag_code: Optional[str]
    ) -> str:
        """
        Add standard documentation sections
        """
        header = """# Data Pipeline Documentation

*Auto-generated by DataSherpa*

---

"""
        
        footer = """

---

## Monitoring and Alerts

### Key Metrics to Monitor
- Job execution time
- Data volume processed
- Error rates
- Resource utilization

### Recommended Alerts
- Job failure notifications
- Execution time exceeds threshold
- Data quality issues
- Resource exhaustion warnings

## Maintenance

### Regular Tasks
- Review and optimize Spark configurations
- Clean up old logs and temporary files
- Update dependencies
- Review and update documentation

### Troubleshooting Resources
- Check application logs in `/var/log/spark/`
- Review Spark UI for job details
- Use DataSherpa CLI for automated diagnostics

## Contact

For issues or questions, contact the Data Engineering team.

---

*Last updated: Auto-generated*
"""
        
        return header + llm_docs + footer
